# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
widenet.

SyntaxError: invalid syntax (<ipython-input-3-8ef489505e6a>, line 1)

# Peeking inside the network

In [4]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[ 0.0165,  0.6103],
        [ 0.3274, -0.0661]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.4859, -0.1220], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.3901,  0.4352],
        [-0.1327,  0.0655]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([0.0338, 0.3547], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[ 0.4604, -0.1326],
        [-0.6082,  0.0115],
        [ 0.5382,  0.0439]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.4656,  0.6526, -0.3655], requires_grad=True))
 


In [5]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[ 0.6459, -0.4485],
        [-0.1886,  0.2056],
        [ 0.4651,  0.6455],
        [ 0.0824, -0.0737]], requires_grad=True)
 
Parameter containing:
tensor([ 0.5425,  0.5131,  0.3811, -0.2599], requires_grad=True)
 
Parameter containing:
tensor([[-0.0571,  0.3944, -0.3518, -0.3438],
        [ 0.1010, -0.1166,  0.3091, -0.2132],
        [-0.3550,  0.0872, -0.3335, -0.1759]], requires_grad=True)
 
Parameter containing:
tensor([-0.3820, -0.1378,  0.2635], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [8]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [10]:
# A nice simple way to print out the model info.
!pip install torchinfo
from torchinfo import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!


[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: C:\Users\Lars Moestue\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip


Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1, 3]                    --
├─Linear: 1-1                            [1, 4]                    12
├─Linear: 1-2                            [1, 3]                    15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00